### ISSUE TITLE
Style JSX is not working properly with @media-query

### ISSUE THREAD

**Issue by M1ck0** [zeit/next.js#10505]
# Bug report

## Describe the bug

I am using ```<style jsx>``` to style my components. When that code is compiled ```@media query``` isn't executed successfully. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```css
.post__card .summary {
   width: 351px;
}

@media screen and(max-width: 1142px) {
   .post__card .summary {
       width: 80%;
   }
}
```

## Expected behavior

When code is compiled I have `jsx-2993501484 post__card` and `jsx-2993501484 summary` and JS is looking for 
```css
@media screen and(max-width:1142px) {
    .post__card.jsx-2993501484 .summary.jsx-2993501484 {
        width: 80%;
    }
}
```

But for some reason style from `@media-query` is not applied to the element. That part of `CSS` is not even available in `Inspect element` in browser

## Screenshots

![bug2](https://user-images.githubusercontent.com/19279947/74342295-8dada280-4da9-11ea-878e-b4f463d08e77.png)
![bug](https://user-images.githubusercontent.com/19279947/74342309-93a38380-4da9-11ea-99b5-e36a7712c057.png)

## System information

- OS: **Manjaro Linux**
- Browser: **Chrome**
- Version of Next.js: **^9.1.8-canary.13**
