### ISSUE TITLE
Example `with-scoped-stylesheets-and-postcss` throws error when compositing between files

### ISSUE THREAD

**Issue by thomaslindstrom** [zeit/next.js#1191]
https://github.com/zeit/next.js/tree/master/examples/with-scoped-stylesheets-and-postcss

**Error:**
```
Module build failed: Error: Cannot find module '-!./../node_modules/css-loader/index.js??ref--6-4!./../node_modules/postcss-loader/index.js!../global.css'
```

**Steps to reproduce:**
1. Clone `with-scoped-stylesheets-and-postcss`
2. Create a file `global.css` with a class name `font-sans`
```css
 .font-sans {
   font-family: georgia; /* ;) */
 }
```
3. In `styles.css`, `compose` `font-sans`:
```css
.paragraph {
  composes: font-sans from '../global.css';
}
```
4. `next dev`
