### ISSUE TITLE
Do you guys have a dockerfile for deploying next.js?

### ISSUE THREAD

**Issue by ojosdegris** [zeit/next.js#121]
I have my dokku cluster and would love to deploy it using docker and not buildpacks.

**Comment by ojosdegris** [comment]
Overall, I'd say you guys've beat create-react-app by a lot!

**Comment by ojosdegris** [comment]
FROM node:6-onbuild
    # Create app directory
    RUN mkdir -p /usr/src/app 
    WORKDIR /usr/src/app
    # Install app dependencies
    COPY package.json /usr/src/app/
    RUN npm install
    # Bundle app source
    COPY . /usr/src/app
    RUN npm run build
    EXPOSE 80

As I said I am trying to run this thing on my dokku, and exposing 80 kinda did the trick but now I can not get letsencrypt to work with this new app. Will keep investigating...

**Comment by impronunciable** [comment]
@ojosdegris Thanks for the research. It's really important to be able to deploy this everywhere. In the meanwhile, you can use `now`.

`$ cd your-project`
`$ now`

💥

**Comment by aesopwolf** [comment]
I've made *slight* progress on figuring this out, but hit a roadblock.

.dockerignore:
```
node_modules
npm-debug.log
.next
```

Dockerfile:
```Dockerfile
FROM node:argon

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install
RUN npm run build

# Bundle app source
COPY . /usr/src/app

EXPOSE 3000
CMD [ "npm", "start" ]
```

bash:
```bash
$ docker build -t my-nodejs-app .
$ docker run -it -P  --rm --name my-running-app my-nodejs-app
$ open http://localhost:32770/ # port number found using kitematic ui
```

Finally, I get a 404:
![image](https://cloud.githubusercontent.com/assets/6847633/20782805/16e32354-b744-11e6-953c-d342b1a585d4.png)

**Comment by aesopwolf** [comment]
Ah, I just switched to `node:6-onbuild` instead of `node:argon` and everything worked fine 🎉

Maybe we can add this to the wiki and close this issue?

**Comment by johannchen** [comment]
I used the Dockerfile to build an image.  The image size is 776 MB, is it too big? node:6-onbuild image is already 651 MB. Is there any slimmer node image that works?

**Comment by luisrudge** [comment]
@johannchen try node:alpine

**Comment by rauchg** [comment]
Should work out of the box with any Node docker image. Next doesn't require anything special on top, other than running `npm run build` and `npm run start`.

**Comment by to-kra** [comment]
dont work for me `
> Couldn't find a `pages` directory. Please create one under the project root`

**Comment by sbr464** [comment]
I posted this tutorial which has a node-alpine image

https://medium.com/@sbr464/next-js-tutorial-deploy-to-docker-on-google-cloud-container-engine-6b0c19dd8ecb

**Comment by bigbassroller** [comment]
Here is my Dockerfile: 
```
FROM node:8.0.0-alpine

#Install bash
RUN apk add --update bash && rm -rf /var/cache/apk/* 

#Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

#Install app dependencies
COPY frontend/package.json /usr/src/app/
RUN npm install --no-optional

#Bundle app source
COPY ./frontend /usr/src/app

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
```
and here is my docker-compose.dev.yml
```
version: '3'

services:
 mongo-db:
  container_name: mongo-db
  image: mongo
  ports:
   - 27017
  volumes:
   - ./env/mongo-db:/data/db
  environment:
   PORT: 27017
 frontend:
  container_name: frontend
  build: 
    context: ./
    dockerfile: DockerfileFrontendDev
  ports:
    - "3000:3000"
  volumes:
    - ./frontend:/usr/src/app/
  environment:
   NODE_ENV: 'development'
   PORT: 3000
 api-server:
  container_name: api-server
  build: 
    context: ./
    dockerfile: DockerfileAPIDev
  ports:
    - "4000:4000"
  volumes:
    - ./api-server:/usr/src/app/
  links:
    - mongo-db
  environment:
   NODE_ENV: 'development'
   MONGO_URL: mongodb://mongo-db:27017/mongo-db
   PORT: 4000
```

Everything works with Next and api on the frontend, but I am not able to reach the api from within the container. I get this error: 
```
request to http://localhost:4000/api/users failed, reason: connect ECONNREFUSED 127.0.0.1:4000
FetchError: request to http://localhost:4000/api/users failed, reason: connect ECONNREFUSED 127.0.0.1:4000
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```
