### ISSUE TITLE
Invalid or unexpected token for styles import

### ISSUE THREAD

**Issue by Onibenjo** [zeit/next.js#12611]
# Bug report

```
ready - started server on http://localhost:3000
error - ./assets/scss/nextjs-material-kit.scss
C:\Users\Benjo\MTA\node_modules\style-loader\node_modules\schema-utils\dist\validate.js:1

SyntaxError: Invalid or unexpected token
```

## Describe the bug

I keep getting "Syntax Error: Invalid or unexpected token" whenever I import my scss stylesheet globally in _app.js.
It just brought this error all of a sudden.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start dev server

## Expected behavior

Compiled successfully

## System information

- OS:  Windows
- Version of Next.js: 9.3.5
- Version of Node.js: 13.12.0

**Comment by jamesmosier** [comment]
Can you include a code snippets or a repository? Otherwise this is hard to reproduce...

**Comment by Onibenjo** [comment]
Has to do with the style loader library parsing css import.
I imported a global style in _app.js and it keeps giving errors.
Removing the import fixes it.
I had no code changes or anything

**Comment by jamesmosier** [comment]
I just created a new Next project, imported a `.scss` file in `_app.js` and it worked:

1. `yarn create next-app`
2. `yarn add sass`
3. Added an `pages/_app.js` and `import '../styles/mystyles.scss'`
4. `yarn dev`
5. styles are there when I load the page

So do you have a code snippets or a repository that I could view to see this not working?

**Comment by Onibenjo** [comment]
```javascript
import React from "react";
import App from "next/app";
import Head from "next/head";
import { ThemeProvider } from "@material-ui/core/styles";
import { ToastProvider } from "react-toast-notifications";
import { parseCookies } from "nookies";
import { ProvideAuth } from "../utils/use-auth";

import "../assets/scss/nextjs-material-kit.scss";
import theme from "../theme";
import NProgress from "../components/Progressbar/NProgressBar";

export default class MyApp extends App {
  componentDidMount() {
    const jssStyles = document.querySelector("#jss-server-side");
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }

  render() {
    const { Component, pageProps, router } = this.props;
    const getLayout = Component.getLayout || ((page) => page);

    return (
      <>
        <Head>
          <title>Medtech Africa</title>
          <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
        </Head>
        <ThemeProvider theme={theme}>
          <ToastProvider placement="bottom-right">
            <NProgress />
              <ProvideAuth>{getLayout(<Component {...pageProps} />)}</ProvideAuth>
          </ToastProvider>
        </ThemeProvider>
      </>
    );
  }
}

```

**Comment by Onibenjo** [comment]
removing the import causes no errors

**Comment by jamesmosier** [comment]
Without seeing `nextjs-material-kit.scss` it is hard to say what is causing the issue. It could be some unsupported scss syntax within that file. Are you able to show the contents of `nextjs-material-kit.scss`?

**Comment by Onibenjo** [comment]
Here it is, but I didn't change anything in it, I just installed a couple of dependencies and all of a sudden, loading CSS became a problem.
I was thinking maybe it had something to do with styleloader but I have deleted nodemodules and reinstalled it, tried different versions of nextjs

```css
@import "core/variables";
@import "core/mixins";

// Core Components
@import "core/misc";
@import "core/fonts1"; 

a {
  text-decoration: none;
}

body::-webkit-scrollbar-track
{
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    border-radius: 10px;
    background-color: #F5F5F5;
}

body::-webkit-scrollbar
{
    width: 12px;
    background-color: #F5F5F5;
}

body::-webkit-scrollbar-thumb
{
    border-radius: 5px;
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
    background-color: #00a8e1;
}

* {
  scrollbar-width: thin;
  scrollbar-color: #00a8e1;
}
```
