### ISSUE TITLE
Next.js on Docker doesn't hot reload

### ISSUE THREAD

**Issue by mikenikles** [zeit/next.js#1961]
Hey there,

I recently migrated our Next.js development environment to Docker. This allows us to start up a number of services with a single `docker-compose up` command.

Everything works fine, except for Next.js which doesn't hot-reload anymore. I put together a very simple Github repo which showcases the issue at https://github.com/mikenikles/mikenikles.xyz.

The key files are:

**docker-compose.yml**
```yaml
version: '3'
services:
  mikenikles-frontend:
    build: ./
    command: yarn dev
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
```

**Dockerfile**
```
FROM node:7.7.1

EXPOSE 3000

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json yarn.lock /usr/src/app/
RUN yarn

# Bundle app source
COPY . /usr/src/app
```

**.dockerignore**
```
.next/
node_modules/
npm-debug.log
```

**Note**: When I connect to the docker container and change `pages/index.js` in the container, Next.js hot-reloads as expected. Even when I use my editor to change `pages/index.js`, I can see the file changed in the container, but Next.js doesn't hot-reload.

Has anyone set up something similar?

Thanks,

Mike
