### ISSUE TITLE
Unable to use self-hosted fonts using NextJS

### ISSUE THREAD

**Issue by amitsch666** [zeit/next.js#2645]
I am compiling SCSS and externalizing the resulting CSS into a file using sass-loader and extract-text-webpack-plugin in next.config.js. The compiled CSS file is being emitted into the .next folder. I also have some static resources, i.e. images and fonts that I'm referencing in the stylesheet. These static resources are also being compiled into the .next folder using the file-loader plugin in next.config.js.

However, when the page loads in the browser, I get a 404 on these resources because NextJS seems to prepend their paths with a `/_next/webpack/` in the compiled CSS file:

`http://54.197.22.181/_next/webpack/52a802f51895f840821c1083434f3d84.ttf`

Is there any workaround to this issue? I really need to use SASS and keep the compiled CSS as an external file as against embedded style. So, the CSS-in-JS model isn't what I'm comfortable with.

For reference, my project is hosted at https://github.com/amitsch666/nano.

Here's the relevant rule I have in my next.config.js:

`{ test: /\.(ttf|eot|png)$/, loader: 'file-loader' }`

Here's the font declaration in my scss file:

```
@font-face {
	font-family: 'Lemonada';
	src: url('../static/fonts/Lemonada/Lemonada-Regular.ttf');
	src: url('../static/fonts/Lemonada/Lemonada-Bold.ttf');
	src: url('../static/fonts/Lemonada/Lemonada-SemiBold.ttf');
	src: url('../static/fonts/Lemonada/Lemonada-Light.ttf');
}
```
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Update:** I have managed to make my site work by routing all `_next/webpack/static/` requests to `/.next/static` in my Express middleware. However, this still seems a tad hackish to me and would love to hear if someone has a more "standard" solution.

**Comment by jay-manday** [comment]
Have also been struggling with the same problem, unfortunately @amitsch666's nice solution to use express to serve the font's as a static folder and tried many different things. Deff interested in seeing this feature added.

Thanks!

**Comment by stevefan1999** [comment]
Try to inline your fonts into webpack module by using https://github.com/quadric/babel-plugin-inline-import or https://github.com/elliottsj/babel-inline-import-loader

This would increase the app.js bundle size but maybe that's the only way out

**Comment by arunoda** [comment]
One question?

Cant we use urls like this?

```css
@font-face {
	font-family: 'Lemonada';
	src: url('/static/fonts/Lemonada/Lemonada-Regular.ttf');
	src: url('/static/fonts/Lemonada/Lemonada-Bold.ttf');
	src: url('/static/fonts/Lemonada/Lemonada-SemiBold.ttf');
	src: url('/static/fonts/Lemonada/Lemonada-Light.ttf');
}
```
