### ISSUE TITLE
How to add id to parent div after body and div after the div with id "__next" ?

### ISSUE THREAD

**Issue by gauravarora91** [zeit/next.js#2783]
![screen shot 2017-08-16 at 2 38 30 am](https://user-images.githubusercontent.com/2230579/29336648-17a7d2b8-822c-11e7-8eb0-8aec36f6e6f8.png)

**Comment by JustasPolis** [comment]
If i'm correct, try this

```css
[data-reactroot] {
          height:100%;
        }
```

**Comment by JustasPolis** [comment]
If I assume we're talking about same div :).
```css
[data-reactroot] {
          your-css:
        }
```
