### ISSUE TITLE
Multi plugins not working as result gets overwritten

### ISSUE THREAD

**Issue by jaqua** [zeit/next.js#3861]
I need to use `@zeit/next-css` and `@zeit/next-sass` at the same time, but this is failing by just using `module.exports = withCSS(withSass(...))` as only one type gets compiled.

I'm referencing to the issues 

https://github.com/zeit/next-plugins/issues/34
https://github.com/zeit/next-plugins/issues/69
https://github.com/zeit/next-plugins/issues/58
https://github.com/zeit/next.js/issues/3852

This is a simple example what I'm doing and what the result looks like.

**static/styles/style.css**
```css
#content {
  font-size: 3rem
}
```

**static/styles/style.sass**

```css
#title
  font-size: 1rem
````

**next.config.js**

```javascript
const withCSS = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')

module.exports = withCSS(withSass({
  webpack: (config) => {
    return config
  }
}))
```

**components/Header.js**

```javascript
import Head from 'next/head'
import '/static/styles/style.css'
import '/static/styles/style.sass'

export const Header = props => {
  return (
    <Head>
      <meta httpEquiv='content-type' content='text/html;charset=UTF-8' />
      <meta charSet='utf-8' />
      <title>Title</title>
      <link rel='stylesheet' href='/_next/static/style.css' />
    </Head>
  )
}
```

The result `/.next/static/style.css` content is only:

```css
#content {
  font-size: 1rem
}
/*# sourceMappingURL=style.css.map*/
````

I'm missing the compiled sass file.

If I switch next.config.js to `withSass(withCSS({..}))` the result is only:

```css
#title {
  font-size: 3rem; }
/*# sourceMappingURL=style.css.map*/
````

The map for the last one is:

    {"version":3,"sources":["/Users/project/static/styles/style.sass"],"names":[],"mappings":"AAAA;EACE,gBAAgB,EAAE","file":"static/style.css","sourcesContent":["#title {\n  font-size: 3rem; }\n\n\n\n// WEBPACK FOOTER //\n// ./static/styles/style.sass"],"sourceRoot":""}
