### ISSUE TITLE
Recommended way to do font loading?

### ISSUE THREAD

**Issue by alexpriceonline** [zeit/next.js#512]
I'm using the `<Head>` component to import a Google Fonts stylesheet:

```
<Head>
  <title>Foo</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet" />
</Head>
```

And it works fine on renders *after* the initial render. Unfortunately on the first render I don't get access to Open Sans.

Is there a better way to handle font loading like this? Maybe download the fonts and put them in `/statics`?

**Comment by nkzawa** [comment]
I think this should work. I wonder if the font was loaded before styles.

**Comment by rauchg** [comment]
Like @nkzawa says, that should work. Can you debug a bit more so we understand why it isn't?

**Comment by alexpriceonline** [comment]
I'll have another look tomorrow. I'm on `2.0.0-beta.2` if that changes anything

**Comment by arunoda** [comment]
@alexpriceonline May be send us a sample repo. So, we could see the problem.

**Comment by alexpriceonline** [comment]
It seems to work now... apologies gentlemen 💩

**Comment by HarrisRobin** [comment]
Sorry to re-open this, but is there a better solution than loading fonts externally?

This is not ideal for me as when the page loads, you encounter this when the font is changing: 
![mar-14-2017 7-45-57 pm](https://cloud.githubusercontent.com/assets/3880008/23927261/ff49a4e6-08ee-11e7-94f8-28a336862051.gif)


Being new to SSR, is there a way to load the font on the server to avoid this flash?

**Comment by arunoda** [comment]
@HarrisRobin you could use Custom document and load webfonts inside it. (I mean in the `<head />`)

**Comment by HarrisRobin** [comment]
@arunoda good idea! I'll give it a try and see if it gets rid of the issue :) 

Thanks

**Comment by JuHwon** [comment]
@HarrisRobin did you come up with any solution?
I am having the same issue right now. In my other projects i usually use the typeface packages like typeface-roboto. but i dont know who to configure next.js to also include the fonts into the build.

**Comment by hexsprite** [comment]
@JuHwon @HarrisRobin I came up with a solution that works for me using Webfont Loader via `@dr-kobros/react-webfont-loader`. Basically I set the entire page to not be visible. WFLoader sets `html.wf-active` when all fonts have loaded so that's when the page becomes visible.

**Comment by FaridSafi** [comment]
It works for me using custom `_document.js`

**Comment by kitze** [comment]
@hexsprite how did you do integrate react-webfont-loader with next.js? I get an error that ```window``` is undefined?

**Comment by mraxus** [comment]
We came across this problem as well, with TypeKit.
We were using 'react-typekit' but that did not generate the @font-face styling at all server-side. So we had a glitch of a second or so for every single render.

Our (current) solution is very simple but works nicely, only the first uncached rendering causes a slight FOUT:

```jsx
import Document, { Head, Main, NextScript } from 'next/document'

export default class extends Document {
  static async getInitialProps() {
    ...
  }

  render() {
    return (
      <html lang="en">
        <Head>
          <script src="https://use.typekit.net/xxxxxxx.js" />
          <script dangerouslySetInnerHTML={{ __html: 'try{Typekit.load({ async: false });}catch(e){}' }} />
        </Head>
        <body>
          ...
        </body>
      </html>
    )
  }
}
```

Please add comments or suggestions on this

**Comment by umairfarooq44** [comment]
I am using **react-fa** to load the font but I am getting this error on initial load : 
```Invalid or unexpected token
/home/umair/Projects/next-projs/next/node_modules/font-awesome/css/font-awesome.css:7
@font-face {
^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/umair/Projects/next-projs/next/node_modules/react-fa/lib/index.js:13:1)```

As I have written the loaders in next.config.js , if hmr executes (by changing/editing file) error disappears and page reloads fine but in chrome console , I get this error:
`Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ta-reactid="1"><div data-reactid="2"><st
 (server) ta-reactid="1"><div style="color:#000;ba`
Is there any way to load font without error on first load.

**Comment by rwieruch** [comment]
@kitze did you manage to load the font before the page is rendered?

**Comment by billgloff** [comment]
I'm also getting 'window is not defined' when using  react-webfont-loader     Anyone figure out yet  how to get it integrated into Next?

**Comment by mike3run** [comment]
hey guys, i solved it nor really using webfontloader but by using [fontfaceobserver](https://fontfaceobserver.com)

here is a snippet i did to load roboto from google fonts.

`Fonts.js`

```javascript
const FontFaceObserver = require('fontfaceobserver')

const Fonts = () => {
  const link = document.createElement('link')
  link.href = 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900'
  link.rel = 'stylesheet'

  document.head.appendChild(link)

  const roboto = new FontFaceObserver('Roboto')

  roboto.load().then(() => {
    document.documentElement.classList.add('roboto')
  })
}

export default Fonts
```

Then on my `index.js`

```.javascript
import React from 'react'
import Home from '@/Home'
import Fonts from '~/general/Fonts'

class Index extends React.Component {
  componentDidMount () {
    Fonts()
  }

  render () {
    return <Home />
  }
}

export default Index
```

Boom, non-blocking fonts with a class added later on to the DOM, tested using styled-components as the css solution and got 100/100 on google speed insights

**Comment by tgrecojs** [comment]
I haven't tried this personally but setting the `font-display` property to`optional` may cure text from swapping. Recently learned about this in this google [microtip video](https://www.youtube.com/watch?v=-lPTshDcr7o&t=2s) so thought I would share in case it helps anyone 😄

**Comment by mike3run** [comment]
@tgrecojs i don't think that's a feasible solution:

http://caniuse.com/#feat=css-font-rendering-controls

![screen shot 2017-09-10 at 11 13 30](https://user-images.githubusercontent.com/7088511/30250721-2f8b65c4-9619-11e7-950d-b2e3526c7f4d.png)

**Comment by tgrecojs** [comment]
haha good to know 👍

**Comment by darqueos** [comment]
@mike3run solution worked for me, but I was unable to use **WebFontLoader**.

**Comment by harrisrobin** [comment]
The best solution I have found is to use a custom server, load the fonts and use global stylesheet with postcss-url. It's working out quite well for me with no delay and font change like i was experiencing before.

If anyone wants more details on this solution, you'll find some issues talking about it. If you still need help feel free to reach out and i'll show you the code.

**Comment by neosavvy** [comment]
@harrisrobin would really appreciate a link to the ideal way to do this.

**Comment by harrisrobin** [comment]
@neosavvy can't link to it due to closed source,

but here's all the parts deconstructed:

You will need the following for postcss-url:
postcss.config.js
```js
module.exports = {
  plugins: [
    require("postcss-easy-import")({ prefix: "_" }), // keep this first
    require("postcss-url")({ url: "inline" }),
    require("autoprefixer")({
      /* ...options */
    }) // so imports are auto-prefixed too
  ]
}
```

Place your fonts in /static/ folder 
<img width="359" alt="screenshot 2017-10-16 16 57 37" src="https://user-images.githubusercontent.com/3880008/31634934-207c4bac-b293-11e7-8085-a141926fe616.png">


Simply use @font-face:
global-styles.css
```css
@font-face {
  font-family: "gt_walsheimlight_oblique";
  src: url("/static/fonts/gt-walsheim-light-oblique-webfont.woff2")
      format("woff2"),
    url("/static/fonts/gt-walsheim-light-oblique-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "gt_walsheimlight";
  src: url("/static/fonts/gt-walsheim-light-webfont.woff2") format("woff2"),
    url("/static/fonts/gt-walsheim-light-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "gt_walsheimmedium_oblique";
  src: url("/static/fonts/gt-walsheim-medium-oblique-webfont.woff2")
      format("woff2"),
    url("/static/fonts/gt-walsheim-medium-oblique-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "gt_walsheimmedium";
  src: url("/static/fonts/gt-walsheim-medium-webfont.woff2") format("woff2"),
    url("/static/fonts/gt-walsheim-medium-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "gt_walsheimregular_oblique";
  src: url("/static/fonts/gt-walsheim-regular-oblique-webfont.woff2")
      format("woff2"),
    url("/static/fonts/gt-walsheim-regular-oblique-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "gt_walsheimregular";
  src: url("/static/fonts/gt-walsheim-regular-webfont.woff2") format("woff2"),
    url("/static/fonts/gt-walsheim-regular-webfont.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}
```

Let me know if you have any issues with that @neosavvy
