### ISSUE TITLE
Unable to import certain CSS files (it thinks invalid syntax)

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5378]
# Bug report

## Describe the bug

I am unable to import certain CSS files from node_modules.

## To Reproduce

`npm install slick-carousel` then try

```js
import 'slick-carousel/slick/slick-theme.css'
```

## Expected behavior

It should work.

## Screenshots

It has throws syntax errors on the CSS file, like these:

```
 error  in ./node_modules/slick-carousel/slick/slick-theme.css

Module build failed: ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
    at doBuild (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/webpack/lib/NormalModule.js:303:19)
    at runLoaders (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/webpack/lib/NormalModule.js:209:11)
    at /Users/trusktr/src/Signafy+mapper-public-website/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/trusktr/src/Signafy+mapper-public-website/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at /Users/trusktr/src/Signafy+mapper-public-website/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at /Users/trusktr/src/Signafy+mapper-public-website/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at process._tickCallback (internal/process/next_tick.js:61:11)`
```

## System information
 - Version of Next.js: 6.1.1

## Additional context

If you delete the first few blocks that have `'` characters (f.e. the UTF line and blocks containing `url('')`) then the error goes away.

**Comment by trusktr** [comment]
The parts of the CSS file that cause the problem look like this:

```css
@charset 'UTF-8';
/* Slider */
.slick-loading .slick-list
{
    background: #fff url('./ajax-loader.gif') center center no-repeat;
}

/* Icons */
@font-face
{
    font-family: 'slick';
    font-weight: normal;
    font-style: normal;

    src: url('./fonts/slick.eot');
    src: url('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('svg');
}

```
