### ISSUE TITLE
Nextjs not recompiling with Docker in development

### ISSUE THREAD

**Issue by MatteoGioioso** [zeit/next.js#6417]
# Bug report

## Describe the bug

I am trying to build a development environment for Nextjs with Docker.
Unfortunately looks like Nextjs is not recompiling if any changes happen.

## To Reproduce

Dockerfile:

```
FROM node

WORKDIR /usr/src/app

COPY . .

RUN npm install

CMD [ "npm", "run", "dev" ]
```

Docker-compose.yml

```
version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
```

Everything works correctly Nextjs compile successfully and displays what it should on the browser.
However when I try to change something is my `index.js` it does not recompile
Upon inspecting the container and the open `index.js` it looks like the changed has been applied successfully.

I have google a bit and I found similar linked issues: 
https://github.com/zeit/next.js/issues/1961
https://github.com/zeit/next.js/issues/757
https://github.com/zeit/next.js/pull/823
However they all led to no useful solution.

## Expected behavior
Should recompile

## System information
 - OS: Window 10
 - Version of Next.js: 7.0.3

**Comment by timneutkens** [comment]
> * Version of Next.js: 7.0.3

I'm assuming you mean 8.0.3.

**Comment by timneutkens** [comment]
I'm not sure what to do with this issue, there is not much to fix on the Next.js side of things. I guess docker is not relaying change events into the volume.

Maybe someone from the community has experienced this before.

**Comment by giuseppeg** [comment]
@MatteoGioioso can you try to inspect the network panel and see if it pings correctly? 

<img height="300" alt="screen shot 2019-02-23 at 10 07 39 am" src="https://user-images.githubusercontent.com/711311/53284314-eb894a80-3752-11e9-87b4-adf32d38c599.png">
<img height="300" alt="screen shot 2019-02-23 at 10 06 25 am" src="https://user-images.githubusercontent.com/711311/53284315-ec21e100-3752-11e9-88b9-d3299bb0deb0.png">

**Comment by MatteoGioioso** [comment]
@giuseppeg it just pings only one time
I have tried to expose websocket port, but still nothing

```
module.exports = {
  onDemandEntries: {
    websocketPort: 3007,
  },
};
```
```
ports:
  - "3007:3007"
```

@timneutkens I do not think is Docker, as it is working normally with CRA or similar

**Comment by MatteoGioioso** [comment]
Ok, after hours of trial and error I solved like this

Dockerfile:
```
FROM node

WORKDIR /usr/src/app

COPY . .

RUN npm install

CMD [ "npm", "run", "dev" ]

```

Docker-compose.yml
```
version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
```

next.config.js:
```
module.exports = {
  webpackDevMiddleware: (config) => {
    // Solve compiling problem via vagrant
    config.watchOptions = {
      poll: 1000,   // Check for changes every second
      aggregateTimeout: 300,   // delay before rebuilding
    };
    return config;
  }
};
```

**Comment by russelh15** [comment]
I just ran into this issue. I was able to get it working without touching the next.config.js file. Here's my setup. I'm using Next 8.0.3

**Dockerfile**
```
FROM node:10

#Setup working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

#Install dependencies
COPY package.json yarn.lock ./
RUN yarn install

#Copy source files
COPY . .

#Running the app
CMD ["yarn","dev"]
```

**docker-compose.yml**
```
version: '3'
services:
    web:
      build: .
      volumes:
          - .:/usr/src/app
      ports:
        - 3000:3000
```

**Comment by Galiaf47** [comment]
>   volumes:
>           - .:/usr/src/app

@russelh15 missed "- /usr/src/app/node_modules" volume. This one is actually very important to not mix host modules with container modules. If you run a linux image on windows host as an example.

Also, what exactly in this config solves the issue?

**Comment by codyspring** [comment]
I ran into a similar problem. Below is my working config.

**Dockerfile** (nothing crazy)
```Dockerfile
FROM node:12.16-alpine as development

WORKDIR /usr/src/web

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build
```

**docker-compose.yml** (see comments)
```yaml
services:
  web:
    container_name: next-web
    build:
      context: .
      target: development
    volumes:
      # Required to sync file changes.
      - .:/usr/src/web
      # Required to not break node modules.
      - /usr/src/web/node_modules
      # Required for next to do it's thing.
      - /usr/src/web/.next
    ports:
      - 3000:3000
    command: npm run dev
```

**Comment by shrmaky** [comment]
@codyspring - The above Docker-Compose works for me but the page load time is too slow when i compare with direct yarn dev...

**Comment by mSheerazAhmad** [comment]
I ran into a similar problem. Below is my working config. Thanks, @MatteoGioioso for referencing [#823](https://github.com/vercel/next.js/pull/823)

**Dockerfile**

```Dockerfile
FROM node:alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

CMD ["yarn", "dev"]
```

**docker-compose.yml**

```yml
version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
```

**next.config.js**

```js
module.exports = {
  webpackDevMiddleware: (config) => {
    // Solve compiling problem via vagrant
    config.watchOptions = {
      poll: 1000,   // Check for changes every second
      aggregateTimeout: 300,   // delay before rebuilding
    };
    return config;
  }
};
```
