### ISSUE TITLE
Transition in production

### ISSUE THREAD

**Issue by simon-baehler** [zeit/next.js#7210]
# Bug report

## Describe the bug

When I start Next in dev mode, css il correctly loaded, but when I start it in production (npm run build then npm run start) all css are correctly load expect, my css with transition (you can check it here http://138.197.182.208:3007/). A default css is load (user agent style sheet I think) then my css is load

```css
.debugtransiton{
  background: red;
  color: white;
  transition: background 5s;
  :hover{
    background: #00aced;
    transition: background 5s;
  }
}
```
My div will be first transparent, then after 5sec red then blue if I hover on it.
What I also did, is to remove the 1st transition, it resolve the problem of css "flashing" but I have lost the hover out
## Expected behavior
Avoid the css flash, for the link in the to, the red div shoudl be red directly on load.
## System information
 - OS:  Windows
 - Browser: All
 - Version of Next.js: 8.0.1

Thank you for your help, and sorry for my bad english.
